## Generate new columns for analysis

#### Import libraries and load dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
# load dataset
df = pd.read_csv('../dataset/cleaned_data.csv')
df.head()

,Date,Measure,Borough,Crime Section,Crime group,Outcome,Positive Outcome,Outcome Count,Refresh Date
0,2023-06-01,Business Crime Outcomes,Barking and Dagenham,POSSESSION OF WEAPONS,POSSESSION OF WEAPONS,Investigation Complete; No Suspect Identified....,N,1,2025-06-05
1,2023-06-01,Business Crime Outcomes,Barking and Dagenham,THEFT,OTHER THEFT,Investigation Complete; No Suspect Identified....,N,2,2025-06-05
2,2023-06-01,Business Crime Outcomes,Barking and Dagenham,THEFT,SHOPLIFTING,Named Suspect Identified: Victim Supports Poli...,N,2,2025-06-05
3,2023-06-01,Business Crime Outcomes,Barking and Dagenham,VIOLENCE AGAINST THE PERSON,VIOLENCE WITH INJURY,Named Suspect Identified: Evidential Difficult...,N,2,2025-06-05
4,2023-06-01,Business Crime Outcomes,Barnet,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Named Suspect Identified: Victim Supports Poli...,N,1,2025-06-05

### Create new columns for year, month and day

In [3]:
# convert data type into datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# create new columns
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Weekday'] = df['Date'].dt.day_name()

In [4]:
df.head()

,Date,Measure,Borough,Crime Section,Crime group,Outcome,Positive Outcome,Outcome Count,Refresh Date,Year,Month,Weekday
0,2023-06-01,Business Crime Outcomes,Barking and Dagenham,POSSESSION OF WEAPONS,POSSESSION OF WEAPONS,Investigation Complete; No Suspect Identified....,N,1,2025-06-05,2023,6,Thursday
1,2023-06-01,Business Crime Outcomes,Barking and Dagenham,THEFT,OTHER THEFT,Investigation Complete; No Suspect Identified....,N,2,2025-06-05,2023,6,Thursday
2,2023-06-01,Business Crime Outcomes,Barking and Dagenham,THEFT,SHOPLIFTING,Named Suspect Identified: Victim Supports Poli...,N,2,2025-06-05,2023,6,Thursday
3,2023-06-01,Business Crime Outcomes,Barking and Dagenham,VIOLENCE AGAINST THE PERSON,VIOLENCE WITH INJURY,Named Suspect Identified: Evidential Difficult...,N,2,2025-06-05,2023,6,Thursday
4,2023-06-01,Business Crime Outcomes,Barnet,ARSON AND CRIMINAL DAMAGE,CRIMINAL DAMAGE,Named Suspect Identified: Victim Supports Poli...,N,1,2025-06-05,2023,6,Thursday

### Save data into CSV file

In [5]:
df.to_csv('../dataset/cleaned_data_2.csv', index=False)